In [1]:
import numpy as np
import pandas as pd

In [2]:
max_number_of_tracks = 232
max_number_of_tracks_power_2 = 256
max_number_of_tracks_log_2 = 8
batch_size = 50
file_i = 1
eps = 0.15
verbose = False
save_intermediate = False

store = "/home/kirby/data/binaries-trk-100/"
z0_file = store + "b-0-trk-z0.bin"
pt_file = store + "b-0-trk-pt.bin"
z0 = np.fromfile(z0_file, dtype=np.float32)
pt = np.fromfile(pt_file, dtype=np.float32)

from batched_dbscan import BatchedDBSCAN

db = BatchedDBSCAN(z0, pt, eps, batch_size, max_number_of_tracks, verbose, save_intermediate)

db.fit()

# df_test = pd.DataFrame(db.boundaries_batches[0], columns = ['idx','pts','nextPts','rSum','z0_low','z0_high','noise'])


# print(db.boundaries_batches[0])
# print(db.z0_pv, db.max_pt)

# import json
# with open('merged_list.json', 'w') as f:
#     json.dump(db.merged_list, f, indent=4)

In [3]:
db.z0_batches[0]

array([-6.15, -5.33, -5.16, -4.86, -3.63, -3.63, -3.22, -3.05, -2.99,
       -2.23, -1.99, -1.93, -1.88, -1.7 , -1.64, -1.17, -1.11, -1.11,
       -0.88, -0.88, -0.53, -0.47, -0.47, -0.41, -0.35, -0.06,  0.18,
        0.18,  0.64,  1.  ,  1.35,  2.05,  2.17,  2.34,  2.46,  2.52,
        2.58,  2.64,  2.75,  2.75,  2.81,  3.34,  4.22,  4.92,  4.98,
        5.51,  5.62,  5.86,  6.09,  7.85])

In [4]:
db.pt_batches[0]

array([3.1 , 4.87, 3.78, 1.96, 5.7 , 4.64, 4.11, 2.34, 3.1 , 2.98, 4.49,
       3.16, 3.13, 2.45, 3.2 , 3.31, 2.75, 2.36, 2.62, 2.1 , 2.08, 3.03,
       2.64, 2.74, 1.97, 2.32, 2.05, 2.26, 2.6 , 2.77, 3.75, 2.22, 4.22,
       3.32, 2.46, 3.08, 2.66, 3.46, 2.91, 3.58, 4.55, 3.44, 3.98, 3.77,
       2.32, 3.2 , 3.66, 5.55, 2.43, 2.83])

In [5]:
pd.set_option('display.precision', 2)

In [6]:
pd.DataFrame({'z0':db.z0_batches[0], 'pt':db.pt_batches[0]})

      z0    pt
0  -6.15  3.10
1  -5.33  4.87
2  -5.16  3.78
3  -4.86  1.96
4  -3.63  5.70
5  -3.63  4.64
6  -3.22  4.11
7  -3.05  2.34
8  -2.99  3.10
9  -2.23  2.98
10 -1.99  4.49
11 -1.93  3.16
12 -1.88  3.13
13 -1.70  2.45
14 -1.64  3.20
15 -1.17  3.31
16 -1.11  2.75
17 -1.11  2.36
18 -0.88  2.62
19 -0.88  2.10
20 -0.53  2.08
21 -0.47  3.03
22 -0.47  2.64
23 -0.41  2.74
24 -0.35  1.97
25 -0.06  2.32
26  0.18  2.05
27  0.18  2.26
28  0.64  2.60
29  1.00  2.77
30  1.35  3.75
31  2.05  2.22
32  2.17  4.22
33  2.34  3.32
34  2.46  2.46
35  2.52  3.08
36  2.58  2.66
37  2.64  3.46
38  2.75  2.91
39  2.75  3.58
40  2.81  4.55
41  3.34  3.44
42  4.22  3.98
43  4.92  3.77
44  4.98  2.32
45  5.51  3.20
46  5.62  3.66
47  5.86  5.55
48  6.09  2.43
49  7.85  2.83

In [7]:
db.left_boundaries_batches[0].astype(int)

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1])

In [8]:
list1 = [1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]

In [9]:
list2 = [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [10]:
len(list2)

50

In [11]:
test1= np.array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [12]:
test1

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1])

In [13]:
np.array_equal(test1, db.left_boundaries_batches[0].astype(int))

False

In [14]:
test1

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1])

In [15]:
db.left_boundaries_batches[0].astype(int)

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1])

In [16]:
for i in range(50):
    if test1[i] != db.left_boundaries_batches[0].astype(int)[i]:
        print(i)

26
28
29
30
31
33

In [17]:
bd = pd.read_csv("boundaries_single.txt", sep=" ", names= ["idx","pts","nextPts","z0_low","z0_high","noise"])

In [18]:
bd_real = db.boundaries_batches[0]

In [19]:
bd_real = db.boundaries_batches[0]
bd_real = pd.DataFrame(bd_real, columns = ['idx','pts','nextPts','rSum','z0_low','z0_high','noise'])
bd_real = bd_real.drop(columns=['rSum'])

In [20]:
bd_real.head()

   idx    pts  nextPts  z0_low  z0_high  noise
0  0.0   0.00     3.10   -6.15    -6.15    1.0
1  1.0   3.10     7.98   -5.33    -5.33    1.0
2  2.0   7.98    11.75   -5.16    -5.16    1.0
3  3.0  11.75    13.71   -4.86    -4.86    1.0
4  4.0  13.71    19.42   -3.63    -3.63    0.0

In [21]:
pd.concat([bd_real,bd], axis=1)

,idx,pts,nextPts,z0_low,z0_high,noise,idx,pts,nextPts,z0_low,z0_high,noise
0,0.0,0.00,3.10,-6.15,-6.15,1.0,0,0.00,3.11,-6.15,-6.15e+00,1
1,1.0,3.10,7.98,-5.33,-5.33,1.0,1,3.11,8.00,-5.33,-5.33e+00,1
2,2.0,7.98,11.75,-5.16,-5.16,1.0,2,8.00,11.79,-5.16,-5.16e+00,1
3,3.0,11.75,13.71,-4.86,-4.86,1.0,3,11.79,13.75,-4.86,-4.86e+00,1
4,4.0,13.71,19.42,-3.63,-3.63,0.0,4,13.75,19.47,-3.63,-3.63e+00,0
5,5.0,19.42,24.06,-3.63,-3.22,0.0,5,19.47,24.13,-3.63,-3.22e+00,0
6,6.0,24.06,28.16,-3.22,-3.22,1.0,6,24.13,28.25,-3.22,-3.22e+00,1
7,7.0,28.16,30.50,-3.05,-2.99,0.0,7,28.25,30.59,-3.05,-2.99e+00,0
8,8.0,30.50,33.60,-2.99,-2.23,0.0,8,30.59,33.70,-2.99,-2.23e+00,0
9,9.0,33.60,36.58,-2.23,-2.23,1.0,9,33.70,36.69,-2.23,-2.23e+00,1
10,10.0,36.58,41.08,-1.99,-1.93,0.0,10,36.69,41.19,-1.99,-1.93e+00,0
11,12.0,44.23,47.36,-1.88,-1.70,0.0,12,44.36,47.50,-1.88,-1.70e+00,0
12,13.0,47.36,49.81,-1.70,-1.64,0.0,13,47.50,49.95,-1.70,-1.64e+00,0
13,14.0,49.81,53.01,-1.64,-1.17,0.0,14,49.95,53.16,-1.64,-1.17e+00,0
14,15.0,53.01,56.31,-1.17,-1.11,0.0,15,53.16,56.48,-1.17,-1.11e+00,0
15,17.0,59.07,61.43,-1.11,-0.88,0.0,17,58.84,61.60,-1.11,-8.79e-01,0
16,18.0,61.43,64.05,-0.88,-0.88,0.0,18,61.60,64.24,-0.88,-8.79e-01,0
17,19.0,64.05,66.15,-0.88,-0.53,0.0,19,64.24,66.34,-0.88,-5.27e-01,0
18,20.0,66.15,68.23,-0.53,-0.47,0.0,20,66.34,68.42,-0.53,-4.69e-01,0
19,24.0,76.64,78.60,-0.35,-0.06,0.0,24,76.86,78.83,-0.35,-5.86e-02,0
20,25.0,78.60,80.92,-0.06,-0.06,1.0,25,78.83,81.16,-0.06,-5.86e-02,1
21,26.0,80.92,82.98,0.18,0.18,0.0,26,81.16,83.43,0.18,1.76e-01,0
22,27.0,82.98,85.24,0.18,0.64,0.0,27,83.43,85.48,0.18,6.45e-01,0
23,28.0,85.24,87.84,0.64,0.64,1.0,28,85.48,88.09,0.64,6.45e-01,1
24,29.0,87.84,90.61,1.00,1.00,1.0,29,88.09,90.87,1.00,9.96e-01,1
25,30.0,90.61,94.37,1.35,1.35,1.0,30,90.87,94.64,1.35,1.35e+00,1
26,31.0,94.37,96.59,2.05,2.17,0.0,31,94.64,96.87,2.05,2.17e+00,0
27,32.0,96.59,100.81,2.17,2.34,0.0,32,96.87,101.10,2.17,2.34e+00,0
28,33.0,100.81,104.14,2.34,2.46,0.0,33,101.10,104.44,2.34,2.46e+00,0
29,40.0,122.29,126.84,2.81,3.34,0.0,40,122.64,127.21,2.81,3.34e+00,0
30,41.0,126.84,130.28,3.34,3.34,1.0,41,127.21,130.66,3.34,3.34e+00,1
31,42.0,130.28,134.26,4.22,4.22,1.0,42,130.66,134.65,4.22,4.22e+00,1
32,43.0,134.26,138.03,4.92,4.98,0.0,43,134.65,138.43,4.92,4.98e+00,0
33,44.0,138.03,140.36,4.98,5.51,0.0,44,138.43,140.76,4.98,5.51e+00,0
34,45.0,140.36,143.55,5.51,5.62,0.0,45,140.76,143.97,5.51,5.62e+00,0
35,46.0,143.55,147.22,5.62,5.86,0.0,46,143.97,147.64,5.62,5.86e+00,0
36,47.0,147.22,152.76,5.86,5.86,1.0,47,147.64,153.21,5.86,5.86e+00,1
37,48.0,152.76,155.19,6.09,6.09,1.0,48,153.21,155.64,6.09,6.09e+00,1
38,49.0,155.19,158.02,7.85,7.85,1.0,49,155.64,155.64,7.85,3.12e-42,1
39,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
40,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
41,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
42,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
43,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
44,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
45,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
46,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
47,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
48,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0
49,50.0,0.00,0.00,21.00,21.00,0.0,50,0.00,0.00,21.00,2.10e+01,0

In [22]:
bd

    idx     pts  nextPts  z0_low   z0_high  noise
0     0    0.00     3.11   -6.15 -6.15e+00      1
1     1    3.11     8.00   -5.33 -5.33e+00      1
2     2    8.00    11.79   -5.16 -5.16e+00      1
3     3   11.79    13.75   -4.86 -4.86e+00      1
4     4   13.75    19.47   -3.63 -3.63e+00      0
5     5   19.47    24.13   -3.63 -3.22e+00      0
6     6   24.13    28.25   -3.22 -3.22e+00      1
7     7   28.25    30.59   -3.05 -2.99e+00      0
8     8   30.59    33.70   -2.99 -2.23e+00      0
9     9   33.70    36.69   -2.23 -2.23e+00      1
10   10   36.69    41.19   -1.99 -1.93e+00      0
11   12   44.36    47.50   -1.88 -1.70e+00      0
12   13   47.50    49.95   -1.70 -1.64e+00      0
13   14   49.95    53.16   -1.64 -1.17e+00      0
14   15   53.16    56.48   -1.17 -1.11e+00      0
15   17   58.84    61.60   -1.11 -8.79e-01      0
16   18   61.60    64.24   -0.88 -8.79e-01      0
17   19   64.24    66.34   -0.88 -5.27e-01      0
18   20   66.34    68.42   -0.53 -4.69e-01      0
19   24   76.86    78.83   -0.35 -5.86e-02      0
20   25   78.83    81.16   -0.06 -5.86e-02      1
21   26   81.16    83.43    0.18  1.76e-01      0
22   27   83.43    85.48    0.18  6.45e-01      0
23   28   85.48    88.09    0.64  6.45e-01      1
24   29   88.09    90.87    1.00  9.96e-01      1
25   30   90.87    94.64    1.35  1.35e+00      1
26   31   94.64    96.87    2.05  2.17e+00      0
27   32   96.87   101.10    2.17  2.34e+00      0
28   33  101.10   104.44    2.34  2.46e+00      0
29   40  122.64   127.21    2.81  3.34e+00      0
30   41  127.21   130.66    3.34  3.34e+00      1
31   42  130.66   134.65    4.22  4.22e+00      1
32   43  134.65   138.43    4.92  4.98e+00      0
33   44  138.43   140.76    4.98  5.51e+00      0
34   45  140.76   143.97    5.51  5.62e+00      0
35   46  143.97   147.64    5.62  5.86e+00      0
36   47  147.64   153.21    5.86  5.86e+00      1
37   48  153.21   155.64    6.09  6.09e+00      1
38   49  155.64   155.64    7.85  3.12e-42      1
39   50    0.00     0.00   21.00  2.10e+01      0
40   50    0.00     0.00   21.00  2.10e+01      0
41   50    0.00     0.00   21.00  2.10e+01      0
42   50    0.00     0.00   21.00  2.10e+01      0
43   50    0.00     0.00   21.00  2.10e+01      0
44   50    0.00     0.00   21.00  2.10e+01      0
45   50    0.00     0.00   21.00  2.10e+01      0
46   50    0.00     0.00   21.00  2.10e+01      0
47   50    0.00     0.00   21.00  2.10e+01      0
48   50    0.00     0.00   21.00  2.10e+01      0
49   50    0.00     0.00   21.00  2.10e+01      0

In [23]:
c_cpp = pd.read_csv("clusters_cpp.txt", sep = ' ', names = ['z0_low','z0_high','pt_sum','noise'])

In [24]:
c_cpp.shape

(32, 4)

In [25]:
c_cpp

    z0_low  z0_high  pt_sum  noise
0    -6.15    -6.15    3.11      1
1    -5.33    -5.33    4.89      1
2    -5.16    -5.16    3.79      1
3    -4.86    -4.86    1.97      1
4    -3.63    -3.63   10.37      0
5    -3.22    -3.22    4.12      1
6    -3.05    -2.99    5.46      0
7    -2.23    -2.23    2.99      1
8    -1.99    -1.88   10.81      0
9    -1.70    -1.64    5.67      0
10   -1.17    -1.11    8.44      0
11   -0.88    -0.88    4.74      0
12   -0.53    -0.35   12.49      0
13   -0.06    -0.06    2.33      1
14    0.18     0.18    4.33      0
15    0.64     0.64    2.61      1
16    1.00     1.00    2.78      1
17    1.35     1.35    3.77      1
18    2.05     2.17    6.46      0
19    2.34     2.81   26.11      0
20    3.34     3.34    3.44      1
21    4.22     4.22    3.99      1
22    4.92     4.98    6.11      0
23    5.51     5.62    6.88      0
24    5.86     5.86    5.56      1
25    6.09     6.09    2.43      1
26    7.85     7.85    0.00      1
27   21.00    21.00    0.00      0
28   21.00    21.00    0.00      0
29   21.00    21.00    0.00      0
30   21.00    21.00    0.00      0
31   21.00    21.00    0.00      0

In [26]:
c_py = pd.DataFrame(db.clusters_batches[0], columns = ['pt_sum','z0_low','z0_high','noise'])

In [27]:
c_py

    pt_sum  z0_low  z0_high  noise
0     3.10   -6.15    -6.15    1.0
1     4.87   -5.33    -5.33    1.0
2     3.78   -5.16    -5.16    1.0
3     1.96   -4.86    -4.86    1.0
4    10.34   -3.63    -3.63    0.0
5     4.11   -3.22    -3.22    1.0
6     5.44   -3.05    -2.99    0.0
7     2.98   -2.23    -2.23    1.0
8    10.78   -1.99    -1.88    0.0
9     5.65   -1.70    -1.64    0.0
10    8.42   -1.17    -1.11    0.0
11    4.72   -0.88    -0.88    0.0
12   12.46   -0.53    -0.35    0.0
13    2.32   -0.06    -0.06    1.0
14    4.31    0.18     0.18    0.0
15    2.60    0.64     0.64    1.0
16    2.77    1.00     1.00    1.0
17    3.75    1.35     1.35    1.0
18    6.45    2.05     2.17    0.0
19   26.03    2.34     2.81    0.0
20    3.44    3.34     3.34    1.0
21    3.98    4.22     4.22    1.0
22    6.10    4.92     4.98    0.0
23    6.86    5.51     5.62    0.0
24    5.55    5.86     5.86    1.0
25    2.43    6.09     6.09    1.0
26    2.83    7.85     7.85    1.0
27    0.00   21.00    21.00    0.0
28    0.00   21.00    21.00    0.0
29    0.00   21.00    21.00    0.0
30    0.00   21.00    21.00    0.0
31    0.00   21.00    21.00    0.0
32    0.00   21.00    21.00    0.0
33    0.00   21.00    21.00    0.0
34    0.00   21.00    21.00    0.0
35    0.00   21.00    21.00    0.0
36    0.00   21.00    21.00    0.0
37    0.00   21.00    21.00    0.0
38    0.00   21.00    21.00    0.0
39    0.00   21.00    21.00    0.0
40    0.00   21.00    21.00    0.0
41    0.00   21.00    21.00    0.0
42    0.00   21.00    21.00    0.0
43    0.00   21.00    21.00    0.0
44    0.00   21.00    21.00    0.0
45    0.00   21.00    21.00    0.0
46    0.00   21.00    21.00    0.0
47    0.00   21.00    21.00    0.0
48    0.00   21.00    21.00    0.0
49    0.00   21.00    21.00    0.0

In [28]:
for i in range(32):
    cpp = c_cpp.iloc[i]
    py = c_py.iloc[i]

    print(f"{i}: ", round(cpp['z0_low'], 2), round(py['z0_low'], 2), round(cpp['z0_high'], 2), round(py['z0_high'], 2), round(cpp['pt_sum'], 2), round(py['pt_sum'], 2), cpp['noise'], py['noise'])

0:  -6.15 -6.15 -6.15 -6.15 3.11 3.1 1.0 1.0
1:  -5.33 -5.33 -5.33 -5.33 4.89 4.87 1.0 1.0
2:  -5.16 -5.16 -5.16 -5.16 3.79 3.78 1.0 1.0
3:  -4.86 -4.86 -4.86 -4.86 1.97 1.96 1.0 1.0
4:  -3.63 -3.63 -3.63 -3.63 10.37 10.34 0.0 0.0
5:  -3.22 -3.22 -3.22 -3.22 4.12 4.11 1.0 1.0
6:  -3.05 -3.05 -2.99 -2.99 5.46 5.44 0.0 0.0
7:  -2.23 -2.23 -2.23 -2.23 2.99 2.98 1.0 1.0
8:  -1.99 -1.99 -1.88 -1.88 10.81 10.78 0.0 0.0
9:  -1.7 -1.7 -1.64 -1.64 5.67 5.65 0.0 0.0
10:  -1.17 -1.17 -1.11 -1.11 8.44 8.42 0.0 0.0
11:  -0.88 -0.88 -0.88 -0.88 4.74 4.72 0.0 0.0
12:  -0.53 -0.53 -0.35 -0.35 12.49 12.46 0.0 0.0
13:  -0.06 -0.06 -0.06 -0.06 2.33 2.32 1.0 1.0
14:  0.18 0.18 0.18 0.18 4.33 4.31 0.0 0.0
15:  0.64 0.64 0.64 0.64 2.61 2.6 1.0 1.0
16:  1.0 1.0 1.0 1.0 2.78 2.77 1.0 1.0
17:  1.35 1.35 1.35 1.35 3.77 3.75 1.0 1.0
18:  2.05 2.05 2.17 2.17 6.46 6.45 0.0 0.0
19:  2.34 2.34 2.81 2.81 26.11 26.03 0.0 0.0
20:  3.34 3.34 3.34 3.34 3.44 3.44 1.0 1.0
21:  4.22 4.22 4.22 4.22 3.99 3.98 1.0 1.0
22:  4.92 4.92 4.98 4.98 6.11 6.1 0.0 0.0
23:  5.51 5.51 5.62 5.62 6.88 6.86 0.0 0.0
24:  5.86 5.86 5.86 5.86 5.56 5.55 1.0 1.0
25:  6.09 6.09 6.09 6.09 2.43 2.43 1.0 1.0
26:  7.85 7.85 7.85 7.85 0.0 2.83 1.0 1.0
27:  21.0 21.0 21.0 21.0 0.0 0.0 0.0 0.0
28:  21.0 21.0 21.0 21.0 0.0 0.0 0.0 0.0
29:  21.0 21.0 21.0 21.0 0.0 0.0 0.0 0.0
30:  21.0 21.0 21.0 21.0 0.0 0.0 0.0 0.0
31:  21.0 21.0 21.0 21.0 0.0 0.0 0.0 0.0

In [29]:
print(c_cpp.iloc[26])

z0_low     7.85
z0_high    7.85
pt_sum     0.00
noise      1.00
Name: 26, dtype: float64

In [30]:
print(c_py.iloc[26])

pt_sum     2.83
z0_low     7.85
z0_high    7.85
noise      1.00
Name: 26, dtype: float64