In [1]:
### Reloads modules properly
%load_ext autoreload
%autoreload 2
%load_ext lab_black

In [2]:
import os

os.sys.path.append("../")

# Load Features For training

In [32]:
features = [
    "trk_pt",
    "trk_eta",
    "trk_phi",
    "trk_z0",
    # "trk_chi2",
    # "trk_chi2dof",
    # "trk_chi2rphi",
    # "trk_chi2rz",
    # "trk_bendchi2",
    # "trk_nstub",
    # "trk_phiSector",
    # "trk_MVA1",
]

In [4]:
import uproot
import pandas as pd
import numpy as np

In [5]:
f = uproot.open("/media/lucas/QS/l1_nnt/OldKF_TTbar_170K_quality.root")

In [6]:
t = f["L1TrackNtuple/eventTree;1"]

In [7]:
trk = t.arrays(features, library="pd")

In [8]:
trk2 = t.arrays(["trk_chi2", "trk_chi2dof", "trk_chi2rphi", "trk_chi2rz"], library="pd")

In [11]:
trk3 = t.arrays(
    ["trk_bendchi2", "trk_nstub", "trk_phiSector", "trk_MVA1"], library="pd"
)

In [13]:
trk.shape

(40780722, 4)

In [15]:
trk3.shape

(40780722, 4)

In [14]:
trk2.shape

(40780722, 4)

In [10]:
trk2.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 40780722 entries, (0, 0) to (222975, 215)
Data columns (total 4 columns):
 #   Column        Dtype
---  ------        -----
 0   trk_chi2      float32
 1   trk_chi2dof   float32
 2   trk_chi2rphi  float32
 3   trk_chi2rz    float32
dtypes: float32(4)
memory usage: 865.4 MB

In [18]:
df = pd.concat([trk, trk2, trk3], axis=1)

In [20]:
df.to_parquet("/media/lucas/QS/l1_nnt/pv_features.parquet")

In [21]:
df.query("entry==0")

                  trk_pt   trk_eta   trk_phi    trk_z0   trk_chi2  \
entry subentry
0     0         2.623967  1.301414 -0.289234 -0.878906   5.994866
      1         3.435026  0.566814 -0.159267  3.339844  45.105690
      2         3.774908  1.815973 -0.240375  4.921875   9.829946
      3         2.641448 -1.435747 -0.128747 -0.468750   4.197709
      4         2.320653  1.837421  0.032604  4.980469   3.273508
...                  ...       ...       ...       ...        ...
      154       2.026653 -2.021094 -1.062191 -0.410156   1.952274
      155       2.049097 -2.055119 -0.964472 -0.410156   4.751755
      156       2.222179 -2.426809 -0.693084  5.566406   5.226877
      157       2.563973  2.081842 -0.530004 -3.046875   4.023309
      158       2.303798  1.335547 -0.274176  4.804688  88.875465

                trk_chi2dof  trk_chi2rphi  trk_chi2rz  trk_bendchi2  \
entry subentry
0     0            0.999144      2.130341    3.864525      0.320722
      1            5.638211     42.600296    2.505395      0.590445
      2            1.228743      4.909814    4.920131      0.354615
      3            0.524714      0.738454    3.459255      0.618279
      4            0.409188      0.946741    2.326767      1.142646
...                     ...           ...         ...           ...
      154          0.244034      0.952175    1.000099      0.879146
      155          0.593969      3.306499    1.445256      1.676488
      156          0.871146      3.015862    2.211014      1.033161
      157          0.502914      0.613549    3.409760      0.810500
      158         11.109433     86.108612    2.766852      0.652480

                trk_nstub  trk_phiSector  trk_MVA1
entry subentry
0     0                 5              0  0.942428
      1                 6              0  0.701423
      2                 6              0  0.958790
      3                 6              0  0.965898
      4                 6              0  0.985416
...                   ...            ...       ...
      154               6              8  0.986499
      155               6              8  0.950314
      156               5              8  0.964760
      157               6              8  0.974706
      158               6              8  0.636907

[159 rows x 12 columns]

In [24]:
df.reset_index(inplace=True)

In [27]:
df.rename(columns={"entry": "event_number", "subentry": "track_number"}, inplace=True)

In [26]:
df

,entry,subentry,trk_pt,trk_eta,trk_phi,trk_z0,trk_chi2,trk_chi2dof,trk_chi2rphi,trk_chi2rz,trk_bendchi2,trk_nstub,trk_phiSector,trk_MVA1
0,0,0,2.623967,1.301414,-0.289234,-0.878906,5.994866,0.999144,2.130341,3.864525,0.320722,5,0,0.942428
1,0,1,3.435026,0.566814,-0.159267,3.339844,45.105690,5.638211,42.600296,2.505395,0.590445,6,0,0.701423
2,0,2,3.774908,1.815973,-0.240375,4.921875,9.829946,1.228743,4.909814,4.920131,0.354615,6,0,0.958790
3,0,3,2.641448,-1.435747,-0.128747,-0.468750,4.197709,0.524714,0.738454,3.459255,0.618279,6,0,0.965898
4,0,4,2.320653,1.837421,0.032604,4.980469,3.273508,0.409188,0.946741,2.326767,1.142646,6,0,0.985416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40780717,222975,211,2.044568,-2.407456,-0.857553,1.113281,3.577560,0.596260,1.192530,2.385030,0.513029,5,8,0.979447
40780718,222975,212,2.491473,-2.141478,-0.616329,8.847656,10.616512,1.769419,2.645877,7.970635,0.560266,5,8,0.614458
40780719,222975,213,2.669393,2.230316,-0.748241,-0.234375,2.216923,0.277115,1.831933,0.384990,0.704175,6,8,0.984691
40780720,222975,214,3.767222,-1.994298,-0.753691,-4.746094,8.086126,1.347688,4.596621,3.489505,0.807914,5,8,0.814558
40780721,222975,215,1.988538,-2.052655,-0.790385,0.996094,14.568451,1.821056,13.244310,1.324140,0.584202,6,8,0.942560

In [29]:
df.query("event_number==0")

,event_number,track_number,trk_pt,trk_eta,trk_phi,trk_z0,trk_chi2,trk_chi2dof,trk_chi2rphi,trk_chi2rz,trk_bendchi2,trk_nstub,trk_phiSector,trk_MVA1
0,0,0,2.623967,1.301414,-0.289234,-0.878906,5.994866,0.999144,2.130341,3.864525,0.320722,5,0,0.942428
1,0,1,3.435026,0.566814,-0.159267,3.339844,45.105690,5.638211,42.600296,2.505395,0.590445,6,0,0.701423
2,0,2,3.774908,1.815973,-0.240375,4.921875,9.829946,1.228743,4.909814,4.920131,0.354615,6,0,0.958790
3,0,3,2.641448,-1.435747,-0.128747,-0.468750,4.197709,0.524714,0.738454,3.459255,0.618279,6,0,0.965898
4,0,4,2.320653,1.837421,0.032604,4.980469,3.273508,0.409188,0.946741,2.326767,1.142646,6,0,0.985416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,0,154,2.026653,-2.021094,-1.062191,-0.410156,1.952274,0.244034,0.952175,1.000099,0.879146,6,8,0.986499
155,0,155,2.049097,-2.055119,-0.964472,-0.410156,4.751755,0.593969,3.306499,1.445256,1.676488,6,8,0.950314
156,0,156,2.222179,-2.426809,-0.693084,5.566406,5.226877,0.871146,3.015862,2.211014,1.033161,5,8,0.964760
157,0,157,2.563973,2.081842,-0.530004,-3.046875,4.023309,0.502914,0.613549,3.409760,0.810500,6,8,0.974706
158,0,158,2.303798,1.335547,-0.274176,4.804688,88.875465,11.109433,86.108612,2.766852,0.652480,6,8,0.636907

In [30]:
df.query("event_number==1")

,event_number,track_number,trk_pt,trk_eta,trk_phi,trk_z0,trk_chi2,trk_chi2dof,trk_chi2rphi,trk_chi2rz,trk_bendchi2,trk_nstub,trk_phiSector,trk_MVA1
159,1,0,2.085667,0.266370,-0.245917,-2.578125,4.638812,0.579851,0.933923,3.704889,0.681381,6,0,0.978693
160,1,1,3.187484,0.757485,-0.190312,2.812500,7.320885,0.915111,4.571610,2.749274,0.762886,6,0,0.960792
161,1,2,2.119512,-0.136296,-0.057751,-4.042969,7.840812,0.980101,3.816912,4.023900,1.090080,6,0,0.950203
162,1,3,4.098193,0.348379,-0.048535,-0.410156,6.634056,0.829257,3.701277,2.932779,1.802632,6,0,0.945870
163,1,4,2.350128,0.005859,-0.134058,-4.218750,4.860334,0.607542,2.096328,2.764006,0.950771,6,0,0.968698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,1,134,4.248758,-1.752177,-0.439386,3.867188,8.495700,1.061962,4.540136,3.955564,0.401689,6,8,0.958731
294,1,135,2.305712,0.642396,-0.356534,-1.464844,8.203501,1.025438,4.996316,3.207185,1.012996,6,8,0.952831
295,1,136,6.311543,-1.634829,-0.441733,3.457031,3.486614,0.581102,0.616966,2.869647,0.119038,5,8,0.979691
296,1,137,4.192600,0.733278,-0.339090,2.519531,4.441290,0.555161,1.841001,2.600289,1.343075,6,8,0.965291
297,1,138,10.644300,2.362880,-0.523535,-1.757812,1.472965,0.245494,1.143522,0.329442,3.067531,5,8,0.886088

In [31]:
df.query("event_number < 100").to_parquet(
    "/media/lucas/QS/l1_nnt/pv_features_100.parquet"
)